language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository 
